# Copyright 2023 The Protobom Authors
# SPDX-License-Identifier: Apache-2.0

name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write # needed to write releases

    steps:
      - name: Install publish-release
        uses: kubernetes-sigs/release-actions/setup-publish-release@e6fb133b190b7c9ba5ff2f3aa4238df1941d240b # main

      - name: Publish Release
        uses: kubernetes-sigs/release-actions/publish-release@e6fb133b190b7c9ba5ff2f3aa4238df1941d240b # main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
