# Copyright 2023 The Protobom Authors
# SPDX-License-Identifier: Apache-2.0

name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write # needed to write releases

    steps:
      - name: Install publish-release
        uses: kubernetes-sigs/release-actions/setup-publish-release@29913844a1f8d07c3222215deb7a5c55a585ff69 # main

      - name: Publish Release
        uses: kubernetes-sigs/release-actions/publish-release@29913844a1f8d07c3222215deb7a5c55a585ff69 # main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
